const app = document.querySelector('#app');
let ws, state, session = JSON.parse(localStorage.getItem('bluff-session') || 'null'), selected;
function connect(){ ws = new WebSocket(`${location.protocol === 'https:' ? 'wss' : 'ws'}://${location.host}/api/ws`); ws.onopen=()=>{ if(session) send({type:'RECONNECT',...session}); render(); }; ws.onmessage=e=>{const m=JSON.parse(e.data); if(m.type==='STATE'){state=m; render()} if(m.type==='JOINED'){session={code:m.code,playerId:m.playerId};localStorage.setItem('bluff-session',JSON.stringify(session));} if(m.type==='SESSION_EXPIRED'){session=null;state=null;localStorage.removeItem('bluff-session');render()} if(m.type==='ERROR') toast(m.message)}; ws.onclose=()=>setTimeout(connect,1500) }
function send(m){ if(ws?.readyState===1) ws.send(JSON.stringify({...m,...(session||{})})) }
function toast(t){ document.querySelector('.toast')?.remove(); document.body.insertAdjacentHTML('beforeend',`<div class="toast">${t}</div>`); setTimeout(()=>document.querySelector('.toast')?.remove(),3000) }
function esc(v=''){return String(v).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function timer(){ if(!state?.deadline)return ''; const s=Math.max(0,Math.ceil((state.deadline-Date.now())/1000)); return `<div class="timer">⏱ <span data-deadline="${state.deadline}">${s}s</span></div>` }
setInterval(()=>document.querySelectorAll('[data-deadline]').forEach(x=>x.textContent=Math.max(0,Math.ceil((+x.dataset.deadline-Date.now())/1000))+'s'),250);
function shell(content){app.innerHTML=`<section class="card"><div class="brand">BLUFF <i>BLITZ</i></div>${content}</section>`}
function landing(){shell(`<h1>Pick a number. Sell the bluff.</h1><p class="lead">Can you spot the secret number?</p><label>Your display name<input id="name" maxlength="20" placeholder="e.g. Sayan"/></label><button id="create">Create a new room</button><div class="or">OR JOIN A FRIEND</div><label>Room code<input id="code" maxlength="4" placeholder="K7PX"/></label><button class="secondary" id="join" disabled>Join room</button><p class="hint">Only use a room code someone else has shared.</p>`); const nameInput=document.querySelector('#name'), codeInput=document.querySelector('#code'), join=document.querySelector('#join'); codeInput.addEventListener('input',()=>join.disabled=codeInput.value.trim().length!==4); document.querySelector('#create').onclick=()=>send({type:'CREATE',name:nameInput.value}); join.onclick=()=>send({type:'JOIN',name:nameInput.value,code:codeInput.value.toUpperCase()})}
function lobby(){const isHost=state.self.id===state.hostId; shell(`<div class="eyebrow">YOUR ROOM CODE</div><div class="code">${state.code}</div><p class="copy">Share this code with your crew</p><h2>Players <small>${state.players.length}/8</small></h2><ul class="players">${state.players.map(p=>`<li><span class="dot ${p.connected?'':'away'}"></span>${esc(p.name)} ${p.id===state.hostId?'<b>👑 HOST</b>':''}</li>`).join('')}</ul>${isHost?`<button id="start" ${state.players.filter(p=>p.connected).length<2?'disabled':''}>Start game</button><p class="hint">Need at least 2 connected players.</p>`:`<p class="waiting">Waiting for the host to start…</p>`}`); document.querySelector('#start')?.addEventListener('click',()=>send({type:'START'}))}
function answering(){shell(`<div class="top"><span>ROUND ${state.round} / ${state.totalRounds}</span>${timer()}</div><div class="phase">PICK A BLUFF NUMBER</div><h1>${esc(state.prompt)}</h1>${state.self.submitted?`<div class="success">✓ NUMBER SUBMITTED</div><p class="waiting">Waiting for the other players…</p>`:`<label>Your number<input id="answer" type="number" inputmode="numeric" min="1" max="100" step="1" placeholder="1–100"/></label><button id="submit">Submit number</button>`}<p class="progress">${state.players.filter(p=>p.connected).length} players active</p>`); document.querySelector('#submit')?.addEventListener('click',()=>send({type:'ANSWER',answer:document.querySelector('#answer').value}))}
function voting(){shell(`<div class="top"><span>ROUND ${state.round} / ${state.totalRounds}</span>${timer()}</div><div class="phase">WHICH NUMBER IS REAL?</div><h1>${esc(state.prompt)}</h1><p class="lead">Choose the secret number.</p><div class="answers">${state.answers.map((a,i)=>`<button class="answer ${selected===a.id?'selected':''}" data-id="${a.id}" ${state.self.voted?'disabled':''}><b>${String.fromCharCode(65+i)}</b><span>${esc(a.text)}</span></button>`).join('')}</div>${state.self.voted?'<div class="success">✓ VOTE SUBMITTED</div>':`<button id="vote" ${!selected?'disabled':''}>Submit vote</button>`}`); document.querySelectorAll('.answer').forEach(b=>b.onclick=()=>{selected=b.dataset.id;voting()});document.querySelector('#vote')?.addEventListener('click',()=>send({type:'VOTE',answerId:selected}))}
function results(final=false){const board=[...state.players].sort((a,b)=>b.score-a.score); shell(`${final?`<div class="trophy">🏆</div><div class="phase">GAME OVER</div><h1>${state.winners.length>1?'TIE — '+state.winners.join(' & '):state.winners[0]+' WINS!'}</h1>`:`<div class="top"><span>ROUND ${state.round} RESULTS</span>${timer()}</div><div class="phase">THE TRUTH WAS</div><h1>${esc(state.correctAnswer)}</h1>`}<div class="results">${state.options.map(o=>`<div><strong>${esc(o.text)}</strong><span>${o.votes} vote${o.votes===1?'':'s'} · ${esc(o.owner)}</span></div>`).join('')}</div><h2>${final?'Final leaderboard':'Leaderboard'}</h2><ol class="scoreboard">${board.map(p=>`<li><span>${esc(p.name)} ${!final&&state.roundDeltas[p.id]?`<em>+${state.roundDeltas[p.id]}</em>`:''}</span><b>${p.score}</b></li>`).join('')}</ol>${final&&state.self.id===state.hostId?'<button id="again">Play again</button>':''}`);document.querySelector('#again')?.addEventListener('click',()=>send({type:'PLAY_AGAIN'}))}
function render(){if(!state)return landing(); if(state.phase==='LOBBY')return lobby();if(state.phase==='ANSWERING')return answering();if(state.phase==='VOTING')return voting();return results(state.phase==='FINAL_RESULTS')};connect();render();
